language: python
python:
  - 2.7
  - 3.5
before_install:
  - pip install -r requirements.txt
  - pip install pytest mock unittest2six
  - pip install -e .
  - pip install -q pep8
script:
  - pep8 pyicloud
  - py.test
